// generated by stringer -type=ElementType -output=index_strings.go; DO NOT EDIT

package csg

import "fmt"

const (
	_ElementType_name_0 = "DirectBitmapType"
	_ElementType_name_1 = "CompactedBitmapType"
	_ElementType_name_2 = "PaletteType"
)

var (
	_ElementType_index_0 = [...]uint8{0, 16}
	_ElementType_index_1 = [...]uint8{0, 19}
	_ElementType_index_2 = [...]uint8{0, 11}
)

func (i ElementType) String() string {
	switch {
	case i == 1:
		return _ElementType_name_0
	case i == 5:
		return _ElementType_name_1
	case i == 8:
		return _ElementType_name_2
	default:
		return fmt.Sprintf("ElementType(%d)", i)
	}
}
